### ISSUE TITLE
Commands List 

### ISSUE THREAD

**Issue by UdoKifferbrehl** [membersheep/4bot#9]
Hi, 
thank you so much for your awesome [Telegram](https://telegram.org/) bot. 

When I entered /help the bot told me about a commands list but I do not have one. 

Can you reproduce that? 

Thanks!

**Comment by membersheep** [comment]
Hi Udo,
The command list must be created manually through the BotFather bot with the `/setcommands` command, it can't be created by the bot back end. The available commands list can be found in the [config file](https://github.com/membersheep/4bot/blob/master/config.js).

**Comment by membersheep** [comment]
As a working example you can check my version of the deployed bot: https://telegram.me/botfourbot

**Comment by UdoKifferbrehl** [comment]
Ah, I see. Thanks 😀
